<div class="row">
    <div class="col l6 m8 s12 offset-l3 offset-m2">
        <div class="card-panel red darken-4 white-text center">
            <div class="row">
                <div class="col s6 offset-s3">
                    <h1 class="card-title center"><i class="large material-icons">error</i>Erreur 404</h1>
                        <p>La page que vous recherchez n’existe pas.</p>
                        <p>Revenez sur le Tableau de bord et essayez à nouveau.</p>
                </div>
            </div>
        </div>
    </div>
</div>
