<h1>Ajouter une recette</h1>

<form method="post" enctype="multipart/form-data">
    <div class="row">
        <div class="input-field col s12">
            <input type="text" name="title" id="title">
            <label for="title">Titre de la recette</label>
        </div>

        <div class="input-field col s12">
            <p>Ingrédients</p>
            <textarea name="ingredients" id="ingredients" class="materialize-textarea editor"></textarea>
            <label for="ingredients"></label>
        </div>

        <div class="input-field col s12">
            <p>Description</p>
            <textarea name="description" id="description" class="materialize-textarea editor"></textarea>
            <label for="description"></label>
        </div>

        <div class="col s12">
            <div class="file-field input-field">
                <div class="btn col s2">
                    <span>Image</span>
                    <input type="hidden" name="MAX_FILE_SIZE" value="2000000" />
                    <input type="file" name="picture" accept="image/png, image/jpeg, image/jpg, image/gif, image/PNG, image/JPG, image/JPEG, image/GIF"/>
                </div>
                <input type="text" name="picture" class="file-path validate" placeholder="Veuillez choisir une image au format png, jpg, jpeg ou gif | Taille maximale 2 Mo"/>
            </div>
            <?php if (!empty($error)): ?>
            <div class="card red">
                <div class="card-content white-text center">
                    <p><?php echo $error; ?></p>
                </div>
            </div>
            <?php endif; ?>
        </div>

        <div class="input-field col s6">
            <select id="category_id" name="category_id">
                <option value="1" selected>Catégories</option>
                <?php foreach ($categories as $category): ?>
                <option value="<?= $category->id; ?>"><?= $category->category_name; ?></option>
                <?php endforeach; ?>
            </select>
        </div>

        <div class="col s6 right-align">
            <p><i class="Tiny material-icons">visibility_off</i>Public<i class="material-icons Tiny">visibility</i></p>
            <div class="switch">
                <label>
                    Non
                    <input type="checkbox" name="public">
                    <span class="lever"></span>
                    Oui
                </label>
            </div>
        </div>

        <div class="col s12">
            <br><br>
            <button class="btn" type="submit" name="addRecipe">Enregistrer</button>
        </div>
    </div>
</form>

