<div class="row">
    <div class="col l4 m6 s12 offset-l4 offset-m3">
        <div class="card-panel">
            <div class="row">
                <div class="col s6 offset-s3">
                    <img src="../public/img/modo.png" alt="Modérateur" width="100%">
                </div>
            </div>

            <h4>Choisir un mot de passe</h4>
            <?php if (!empty($errors)): ?>
                <div class="card red">
                    <div class="card-content white-text center">
                        <?php foreach ($errors as $error) echo "<p>".$error."</p>"; ?>
                    </div>
                </div>
            <?php endif; ?>
            <form method="post">
                <div class="row">
                    <div class="input-field col s12">
                        <input type="password" id="password" name="password" required/>
                        <label for="password">Mot de passe</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <input type="password" id="password_again" name="password_again"/>
                        <label for="password_again">Repéter le mot de passe</label>
                    </div>
                </div>

                <button type="submit" name="submit" class="waves-effect waves-light btn"><i class="material-icons left">perm_identity</i>Valider</button>
            </form>
        </div>
    </div>
</div>
