<div class="row">
    <div class="col l4 m6 s12 offset-l4 offset-m3">
        <div class="card-panel">
            <div class="row">
                <div class="col s6 offset-s3">
                    <img src="../public/img/modo.png" alt="Modérateur" width="100%">
                </div>
            </div>
            <?php if (!empty($error)): ?>
                <div class="card red">
                    <div class="card-content white-text center">
                        <p><?php echo $error; ?></p>
                    </div>
                </div>
            <?php endif; ?>
            <form method="post">
                <div class="row">
                    <div class="input-field col s12">
                        <input type="email" id="email" name="email" required/>
                        <label for="email">Adresse email</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <input type="text" id="token" name="token"/>
                        <label for="token">Mot de passe</label>
                    </div>
                </div>

                <button type="submit" name="submit" class="waves-effect waves-light btn"><i class="material-icons left">perm_identity</i>Se connecter</button>
            </form>
            <br>
            <a class="btn-small blue-grey" href="admin.php?page=login">Déjà modérateur</a>


        </div>
    </div>
</div>
