<section class="container">

<form method="post">
    <input type="text" name="name" id="form_name" placeholder="Nom" required>
        <div class="error-message"><p></p></div>
    <input type="email" name="email" id="form_email" placeholder="Adresse email" required>
        <div class="error-message"><p></p></div>
    <textarea name="comment" id="form_comment" placeholder="Votre message" required></textarea>
        <div class="error-message"><p></p></div>
    <br>
    <button type="submit" name="submit" id="form_submit">Envoyer</button>
</form>
</section>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script src="../public/js/form.js"></script>