<section class="container" id="slate">
    <figure>
        <a href="index.php?p=slate"><img src="img/slate.jpg" alt="Hamburgers"></a>
        <a href="index.php?p=slate"><figcaption><h1>Sur l'ardoise</h1>Terre de contrastes et de nature, l’Argentine est aussi un pays où l’on se fait plaisir en mangeant. Entre pâtes, empanadas, vins et beaucoup de viande, découvrez la cuisine argentine.</figcaption></a>
    </figure>

    <h2>Cuisine argentine</h2>
    <div class="grid" id="grid">
<?php foreach ($recipes as $recipe): ?>

     <div class="grid_recipe">

<?= '<div class="grid_image" style="background-image:url(\'img/recipes/'.$recipe->picture.'\')"></div>'; ?>
<h3 class="grid_title"><?= $recipe->title ?></h3>
<div class="grid_body">
    <h4><?= $recipe->title ?></h4>
    <P>
<?= substr($recipe->description, 0, 500); ?> <span>- [...]</span>
</P>
<p>
<a href="?p=recipe&id=<?= $recipe->id; ?>" >LIRE PLUS</a>
</p>
</div>
</div>
<?php endforeach; ?>
</div>
</div>

</section>



<script type="text/javascript" src="../public/js/polyfill.js"></script>
<script type="text/javascript" src="../public/js/grid.js"></script>
